// Demo dataset for the static prototype.
// In the full application, these values can be replaced by API responses and a real database.

const RESTAURANTS = [
  {
    id: 1,
    name: "Luna Noodles",
    cuisine: "Chinese",
    priceTier: 1,
    rating: 4.6,
    neighborhood: "Greenwich Village",
    borough: "Manhattan",
    distanceMin: 8,
    openNow: true,
    reservation: false,
    petFriendly: false,
    kidFriendly: true,
    accessibility: true,
    outdoor: false,
    diets: ["vegetarian"],
    vibes: ["late-night", "casual", "spicy", "quick"],
    keywords: ["cheap", "noodles", "spicy", "late", "washington square", "soup"],
    description: "Hand-pulled noodles, spicy broths, and fast casual energy right by campus.",
    traffic: [18, 24, 31, 40, 57, 72, 88, 93, 85, 68, 49, 34],
    x: 44,
    y: 62
  },
  {
    id: 2,
    name: "Violet Table",
    cuisine: "French",
    priceTier: 4,
    rating: 4.8,
    neighborhood: "West Village",
    borough: "Manhattan",
    distanceMin: 16,
    openNow: true,
    reservation: true,
    petFriendly: false,
    kidFriendly: false,
    accessibility: true,
    outdoor: true,
    diets: ["gluten-free"],
    vibes: ["cozy", "date-night", "romantic", "wine"],
    keywords: ["cozy", "date", "wine", "romantic", "reservation"],
    description: "A softly lit neighborhood bistro for date nights and long conversations.",
    traffic: [8, 11, 14, 18, 26, 45, 71, 89, 96, 84, 55, 29],
    x: 35,
    y: 48
  },
  {
    id: 3,
    name: "Halal Hearth",
    cuisine: "Mediterranean",
    priceTier: 2,
    rating: 4.5,
    neighborhood: "Astoria",
    borough: "Queens",
    distanceMin: 28,
    openNow: true,
    reservation: false,
    petFriendly: true,
    kidFriendly: true,
    accessibility: true,
    outdoor: true,
    diets: ["halal"],
    vibes: ["family", "comfort", "casual", "group-friendly"],
    keywords: ["halal", "grill", "casual", "group", "family"],
    description: "Warm flatbreads, charcoal skewers, and a reliable neighborhood feel.",
    traffic: [12, 19, 28, 36, 52, 66, 77, 81, 74, 61, 39, 24],
    x: 76,
    y: 38
  },
  {
    id: 4,
    name: "Studio Sips Café",
    cuisine: "Cafe",
    priceTier: 2,
    rating: 4.4,
    neighborhood: "SoHo",
    borough: "Manhattan",
    distanceMin: 13,
    openNow: true,
    reservation: false,
    petFriendly: true,
    kidFriendly: false,
    accessibility: true,
    outdoor: true,
    diets: ["vegan", "vegetarian", "gluten-free"],
    vibes: ["quiet", "study", "work-friendly", "coffee"],
    keywords: ["study", "quiet", "coffee", "work", "pastry"],
    description: "Laptop-friendly cafe with airy seating, espresso, and vegan pastries.",
    traffic: [35, 58, 75, 83, 79, 70, 63, 58, 44, 31, 18, 10],
    x: 49,
    y: 57
  },
  {
    id: 5,
    name: "Borough Bloom",
    cuisine: "American",
    priceTier: 3,
    rating: 4.7,
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    distanceMin: 26,
    openNow: false,
    reservation: true,
    petFriendly: true,
    kidFriendly: true,
    accessibility: true,
    outdoor: true,
    diets: ["vegetarian"],
    vibes: ["trendy", "brunch", "airy", "group-friendly"],
    keywords: ["brunch", "group", "trendy", "weekend", "patio"],
    description: "Bright all-day dining with brunch energy, patio seating, and crowd-pleasing plates.",
    traffic: [22, 44, 71, 92, 96, 81, 65, 56, 48, 35, 20, 12],
    x: 65,
    y: 55
  },
  {
    id: 6,
    name: "Saffron Quiet",
    cuisine: "Indian",
    priceTier: 2,
    rating: 4.7,
    neighborhood: "East Village",
    borough: "Manhattan",
    distanceMin: 11,
    openNow: true,
    reservation: true,
    petFriendly: false,
    kidFriendly: true,
    accessibility: true,
    outdoor: false,
    diets: ["vegan", "vegetarian", "gluten-free"],
    vibes: ["quiet", "cozy", "comfort", "spicy"],
    keywords: ["quiet", "curry", "spicy", "cozy", "vegetarian"],
    description: "A polished but calm Indian spot with deeply spiced curries and plenty of vegetarian options.",
    traffic: [9, 12, 19, 27, 43, 58, 72, 81, 84, 69, 42, 26],
    x: 56,
    y: 51
  },
  {
    id: 7,
    name: "Green Orbit",
    cuisine: "Vegan",
    priceTier: 2,
    rating: 4.3,
    neighborhood: "Lower East Side",
    borough: "Manhattan",
    distanceMin: 14,
    openNow: true,
    reservation: false,
    petFriendly: true,
    kidFriendly: true,
    accessibility: true,
    outdoor: true,
    diets: ["vegan", "vegetarian", "gluten-free"],
    vibes: ["healthy", "casual", "quick", "bright"],
    keywords: ["vegan", "healthy", "bowl", "plant-based", "quick"],
    description: "Colorful plant-based bowls and smoothies for a lighter weekday reset.",
    traffic: [25, 38, 54, 68, 71, 64, 58, 46, 33, 22, 14, 8],
    x: 59,
    y: 63
  },
  {
    id: 8,
    name: "Midnight Katsu",
    cuisine: "Japanese",
    priceTier: 2,
    rating: 4.5,
    neighborhood: "Koreatown",
    borough: "Manhattan",
    distanceMin: 18,
    openNow: true,
    reservation: false,
    petFriendly: false,
    kidFriendly: false,
    accessibility: true,
    outdoor: false,
    diets: [],
    vibes: ["late-night", "crispy", "casual", "comfort"],
    keywords: ["late", "katsu", "crispy", "ramen", "night"],
    description: "Open late with crispy cutlets, hearty bowls, and easy walk-in energy.",
    traffic: [7, 10, 13, 18, 26, 39, 58, 79, 95, 99, 86, 57],
    x: 52,
    y: 41
  },
  {
    id: 9,
    name: "Harbor Mezze",
    cuisine: "Middle Eastern",
    priceTier: 3,
    rating: 4.9,
    neighborhood: "Brooklyn Heights",
    borough: "Brooklyn",
    distanceMin: 31,
    openNow: true,
    reservation: true,
    petFriendly: false,
    kidFriendly: true,
    accessibility: true,
    outdoor: true,
    diets: ["halal", "vegetarian"],
    vibes: ["date-night", "group-friendly", "share-plates", "elevated"],
    keywords: ["mezze", "share", "date", "halal", "beautiful"],
    description: "Elegant mezzes and charcoal mains suited for celebrations or long dinners.",
    traffic: [6, 9, 12, 17, 24, 38, 61, 79, 90, 88, 63, 35],
    x: 61,
    y: 71
  },
  {
    id: 10,
    name: "Copper Pizza Lab",
    cuisine: "Italian",
    priceTier: 3,
    rating: 4.6,
    neighborhood: "Chelsea",
    borough: "Manhattan",
    distanceMin: 19,
    openNow: false,
    reservation: true,
    petFriendly: true,
    kidFriendly: true,
    accessibility: true,
    outdoor: true,
    diets: ["vegetarian"],
    vibes: ["group-friendly", "casual", "date-night", "crispy"],
    keywords: ["pizza", "date", "group", "wine", "chelsea"],
    description: "Wood-fired pies, natural wine, and a lively modern neighborhood crowd.",
    traffic: [12, 18, 23, 29, 42, 57, 75, 88, 91, 76, 48, 26],
    x: 46,
    y: 35
  },
  {
    id: 11,
    name: "Canal Heatpot",
    cuisine: "Chinese",
    priceTier: 3,
    rating: 4.7,
    neighborhood: "Chinatown",
    borough: "Manhattan",
    distanceMin: 17,
    openNow: true,
    reservation: true,
    petFriendly: false,
    kidFriendly: true,
    accessibility: false,
    outdoor: false,
    diets: ["halal"],
    vibes: ["spicy", "group-friendly", "buzzing", "late-night"],
    keywords: ["hotpot", "spicy", "group", "late", "canal"],
    description: "A bustling hotpot favorite for bold flavors and big-table dinners.",
    traffic: [10, 15, 20, 25, 38, 55, 70, 83, 94, 92, 71, 44],
    x: 54,
    y: 67
  },
  {
    id: 12,
    name: "North Star Deli",
    cuisine: "Sandwiches",
    priceTier: 1,
    rating: 4.2,
    neighborhood: "Upper West Side",
    borough: "Manhattan",
    distanceMin: 35,
    openNow: true,
    reservation: false,
    petFriendly: true,
    kidFriendly: true,
    accessibility: true,
    outdoor: false,
    diets: ["gluten-free"],
    vibes: ["quick", "casual", "classic", "budget"],
    keywords: ["cheap", "sandwich", "quick", "budget", "classic"],
    description: "Budget-friendly sandwiches and soups with an old-school neighborhood feel.",
    traffic: [28, 42, 56, 61, 58, 49, 43, 36, 29, 23, 14, 9],
    x: 40,
    y: 18
  }
];

const ALL_VIBES = [
  "cozy",
  "date-night",
  "quiet",
  "study",
  "late-night",
  "group-friendly",
  "trendy",
  "healthy",
  "casual",
  "spicy",
  "romantic"
];

const ALL_DIETS = ["vegan", "halal", "gluten-free", "vegetarian"];

/* ---------- Home page demo data ---------- */
const HOME_TRAFFIC_RESTAURANTS = {
  saffronQuiet: {
    id: "saffronQuiet",
    name: "Saffron Quiet",
    cuisine: "Indian",
    neighborhood: "East Village",
    distanceMin: 11,
    rating: 4.7,
    traffic: [1, 1, 2, 3, 5, 7, 8, 9, 10, 9, 7, 5, 3]
  },
  studioSips: {
    id: "studioSips",
    name: "Studio Sips Café",
    cuisine: "Cafe",
    neighborhood: "SoHo",
    distanceMin: 9,
    rating: 4.5,
    traffic: [2, 3, 5, 7, 8, 9, 8, 7, 6, 5, 4, 3, 2]
  }
};

const HOME_STARTER_FEED = [
  {
    title: "For you",
    restaurant: "Saffron Quiet",
    meta: "Indian · East Village · 11 min"
  },
  {
    title: "Tonight",
    restaurant: "Canal Heatpot",
    meta: "Chinese · Chinatown · 17 min"
  },
  {
    title: "Quiet study",
    restaurant: "Studio Sips Café",
    meta: "Cafe · SoHo · 9 min"
  },
  {
    title: "Worth the trip",
    restaurant: "Harbor Mezze",
    meta: "Middle Eastern · Brooklyn Heights · 31 min"
  }
];

const HOME_SAVED_CUISINES = [
  { cuisine: "Indian", count: 1 },
  { cuisine: "Cafe", count: 1 }
];

const TRAFFIC_LABELS = [
  "11a",
  "12p",
  "1p",
  "2p",
  "3p",
  "4p",
  "5p",
  "6p",
  "7p",
  "8p",
  "9p",
  "10p",
  "11p"
];
